name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: create build dir
        run: mkdir build
      - name: cmake configure
        run: cmake -S test -G Ninja -B build/
      - name: build
        run: cmake --build build
      - name: Test SubBitPackedArrayTest
        run: build/SubBitPackedArrayTest
      - name: Test SubBitPackedArrayNoExceptionsTest
        run: build/SubBitPackedArrayNoExceptionsTest
