name: C/C++ CI

on:
  push:
    branches: ["testing"]
  pull_request:
    branches: ["testing"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: "."
          extensions: "h,hpp,cpp"
          clangFormatVersion: 16

      # BitPackedArray Tests
      - name: create build dir
        run: mkdir build
      - name: cmake configure
        run: cmake -S tests/BitPackedArray -G Ninja -B build/
      - name: build BitPackedArray
        run: cmake --build build
      - name: Test BitPackedArrayTest
        run: build/BitPackedArrayTest
      - name: Test BitPackedArrayNoExceptionTest
        run: build/BitPackedArrayNoExceptionTest

      # SubBitPackedArray Tests
      - name: clear build dir
        run: rm -rf build/*
      - name: cmake configure
        run: cmake -S tests/SubBitPackedArray -G Ninja -B build/
      - name: build SubBitPackedArray
        run: cmake --build build
      - name: Test SubBitPackedArrayTest
        run: build/SubBitPackedArrayTest
      - name: Test SubBitPackedArrayNoExceptionTest
        run: build/SubBitPackedArrayNoExceptionTest

      # SuperBitPackedArray Tests
      - name: clear build dir
        run: rm -rf build/*
      - name: cmake configure
        run: cmake -S tests/SuperBitPackedArray -G Ninja -B build/
      - name: build SuperBitPackedArray
        run: cmake --build build
      - name: Test SuperBitPackedArrayTest
        run: build/SuperBitPackedArrayTest
      - name: Test SuperBitPackedArrayNoExceptionTest
        run: build/SuperBitPackedArrayNoExceptionTest

      # SubBitPackedStruct Tests
      - name: clear build dir
        run: rm -rf build/*
      - name: cmake configure
        run: cmake -S tests/SubBitPackedStruct -G Ninja -B build/
      - name: build SubBitPackedStruct
        run: cmake --build build
      - name: Test SubBitPackedStructTest
        run: build/SubBitPackedStructTest
      - name: Test SubBitPackedStructNoExceptionTest
        run: build/SubBitPackedStructNoExceptionTest

      # SubBitPackedStructArray Tests
      - name: clear build dir
        run: rm -rf build/*
      - name: cmake configure
        run: cmake -S tests/SubBitPackedStructArray -G Ninja -B build/
      - name: build SubBitPackedStructArray
        run: cmake --build build
      - name: Test SubBitPackedStructArrayTest
        run: build/SubBitPackedStructArrayTest
      - name: Test SubBitPackedStructArrayNoExceptionTest
        run: build/SubBitPackedStructArrayNoExceptionTest

      ## SuperBitPackedStructArray Tests
      - name: clear build dir
        run: rm -rf build/*
      - name: cmake configure
        run: cmake -S tests/SuperBitPackedStructArray -G Ninja -B build/
      - name: build SuperBitPackedStructArray
        run: cmake --build build
      - name: Test SuperBitPackedStructArrayTest
        run: build/SuperBitPackedStructArrayTest
      - name: Test SuperBitPackedStructArrayNoExceptionTest
        run: build/SuperBitPackedStructArrayNoExceptionTest
